[package]
name = "xi-core"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]

[dependencies]
serde = "*"
serde_json = "*"
time = "0.1"

[dependencies.xi-rope]
path = "rope"

[dependencies.xi-unicode]
path = "unicode"
